---
Offer:
  from: uuid
  to: call_id
  create_new: true
  sip_addr: true
Ringing:
  from: uuid
  to: uuid
Answer:
  from: uuid
  to: uuid
Join:
  from: uuid
  to: call_id
Unjoined:
  from: uuid
  to: call_id
Input:
  from: adhearsion
  to: uuid
Output:
  from: adhearsion
  to: uuid
Hangup:
  from: uuid
  to: uuid
InputComplete:
  from: uuid
  to: adhearsion
  value: interpretation
