development:
  host: localhost
  database: ahn_logviz_development

test:
  host: localhost
  database: ahn_logviz_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOID_HOST'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
